[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-8_x']

[phases.install]
cmds = [
  'npm install --no-package-lock'
]

[phases.build]
cmds = [
  'npx tsc --version',
  'npm run clean',
  'npx tsc'
]

[start]
cmd = 'npm start'