[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-8_x']

[phases.install]
cmds = [
  'npm install --no-package-lock'
]

[phases.build]
cmds = [
  'npm run typecheck',
  'npm run build'
]

[start]
cmd = 'npm start'