name: 🐛 Bug Report
description: Report a bug in the AI-Enhanced Workflow system
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: dropdown
    id: practitioner-style
    attributes:
      label: Related Practitioner Style
      description: Which practitioner style area does this bug affect?
      options:
        - Uncle Bob (Clean Code)
        - Kent Beck (TDD)
        - Martin Fowler (Refactoring)
        - Jessica Kerr (Functional)
        - Kelsey Hightower (Cloud-Native)
        - General System
        - Not Sure
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Run command '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g., Windows 11, macOS 14, Ubuntu 22.04]
        - Node.js version: [e.g., 18.17.0]
        - NPM version: [e.g., 9.6.7]
        - VS Code version: [e.g., 1.84.2]
        - Claude Code version: [e.g., 0.1.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add any error logs or console output
      placeholder: Paste error logs here...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help...

  - type: checkboxes
    id: ai-assistance
    attributes:
      label: AI Assistance Used
      description: Did you use AI assistance when encountering this bug?
      options:
        - label: I was using Claude Code when this bug occurred
        - label: I was using the MCP server when this bug occurred
        - label: This bug affects AI-generated code
        - label: This bug affects style selection
        - label: No AI assistance was involved
